version: "3.8"

services:
  app:
    image: devdockr18/recruiting-qa-challenge-qa-server:latest
    ports:
      - "8000:8000"
    environment:
      - ENV_VARIABLE=dev
    entrypoint: ["python", "/app/application.py"]
